s=set()
s1=int(input("Enter a number :"))
s.add(s1)
s2=int(input("Enter a number :"))
s.add(s2)
s3=int(input("Enter a number :"))
s.add(s3)
s4=int(input("Enter a number :"))
s.add(s4)
s5=int(input("Enter a number :"))
s.add(s5)
s6=int(input("Enter a number :"))
s.add(s6)
s7=int(input("Enter a number :"))
s.add(s7)
s8=int(input("Enter a number :"))
s.add(s8)
print(s)